[package]
name = "verifier"
version.workspace = true
edition.workspace = true

[dependencies]
bytes = { path = "../bytes" }
graph = { path = "../graph" }
rand = { workspace = true }
sudoku = { path = "../sudoku" }
ureq = "3.0.10"
