[package]
name = "graph"
version.workspace = true
edition.workspace = true

[dependencies]
bytes = { path = "../bytes" }
derive-deftly = { workspace = true }
rand = "0.9.0"
sha2 = { workspace = true }

