[package]
name = "graph"
version.workspace = true
edition.workspace = true

[dependencies]
bytes = { path = "../bytes" }
derive-deftly = { workspace = true }
rand = { workspace = true }
sha2 = "0.10.8"